# Generated by Django 5.2.5 on 2025-08-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_site', '0002_assingment_description_en_assingment_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='test_site.course'),
        ),
        migrations.AlterField(
            model_name='review',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='test_site.course'),
        ),
    ]
